# Generated by Django 5.2 on 2025-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='virgin_login',
            field=models.BooleanField(default=True),
        ),
    ]
