# Generated by Django 5.2 on 2025-05-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/media/products/20240322_200331.jpg', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='Milk Maker', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(upload_to='qr/'),
        ),
    ]
