# Generated by Django 5.2 on 2025-05-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_threshold',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
