# Generated by Django 5.2 on 2025-05-18 08:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_alert_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2025, 5, 18, 16, 3, 8, 72332), verbose_name='Date')),
                ('units', models.IntegerField(verbose_name='Stock Added')),
                ('cpu', models.FloatField(verbose_name='Cost Per Unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
