# Generated by Django 5.2 on 2025-06-08 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_restock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 8, 21, 13, 36, 645456), verbose_name='Date'),
        ),
    ]
