# Generated by Django 5.2.1 on 2025-06-01 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_restock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 1, 13, 38, 18, 695160), verbose_name='Date'),
        ),
    ]
