# Generated by Django 5.2.1 on 2025-06-02 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 3, 0, 16, 32, 734420), verbose_name='Date'),
        ),
    ]
