# Generated by Django 5.2 on 2025-06-11 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 11, 14, 27, 42, 570824), verbose_name='Date'),
        ),
    ]
