# Generated by Django 5.2.1 on 2025-06-03 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 3, 15, 54, 26, 244063), verbose_name='Date'),
        ),
    ]
