# Generated by Django 5.2.2 on 2025-06-09 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 9, 15, 12, 49, 267392), verbose_name='Date'),
        ),
    ]
