# Generated by Django 5.2.2 on 2025-06-11 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 11, 16, 15, 51, 106775), verbose_name='Date'),
        ),
    ]
