# Generated by Django 5.2.2 on 2025-06-14 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_product_timestamp_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 14, 22, 23, 41, 162218), verbose_name='Date'),
        ),
    ]
