# Generated by Django 5.2.2 on 2025-06-14 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 14, 22, 24, 2, 960787), verbose_name='Date'),
        ),
    ]
