# Generated by Django 5.2.2 on 2025-06-16 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 16, 15, 48, 32, 366782), verbose_name='Date'),
        ),
    ]
