# Generated by Django 5.2.2 on 2025-06-16 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 16, 15, 49, 16, 733095), verbose_name='Date'),
        ),
    ]
