# Generated by Django 5.2.2 on 2025-06-17 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 17, 11, 17, 42, 51961), verbose_name='Date'),
        ),
    ]
