# Generated by Django 5.2 on 2025-06-17 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
