# Generated by Django 5.2.2 on 2025-06-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_restock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_img',
            field=models.ImageField(blank=True, null=True, upload_to='barcode/'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
