# Generated by Django 5.2 on 2025-06-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_restock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='1102039gfk', max_length=10, verbose_name='Stock Keeping Unit'),
            preserve_default=False,
        ),
    ]
