# Generated by Django 5.2 on 2025-06-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_product_barcode_img_product_barcode_number'),
        ('inventory', '0022_product_sku'),
    ]

    operations = [
    ]
