# Generated by Django 5.2 on 2025-07-08 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_merge_20250629_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alert_threshold',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be zero or greater.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Value must be zero or greater.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be zero or greater.')], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='restock',
            name='cpu',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Value must be zero or greater.')], verbose_name='Cost Per Unit'),
        ),
        migrations.AlterField(
            model_name='restock',
            name='units',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be zero or greater.')], verbose_name='Stock Added'),
        ),
    ]
