# Generated by Django 5.2.1 on 2025-05-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_info',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
