# Generated by Django 5.2.1 on 2025-05-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_payment_card_info_payment_cvv_payment_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_amount',
        ),
    ]
