# Generated by Django 5.2 on 2025-06-11 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_payment_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.payment'),
            preserve_default=False,
        ),
    ]
