# Generated by Django 5.2.2 on 2025-06-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_payment_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
