# Generated by Django 5.2.2 on 2025-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment',
            field=models.IntegerField(null=True),
        ),
    ]
