# Generated by Django 5.2.2 on 2025-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_cart_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='cart',
            field=models.IntegerField(null=True),
        ),
    ]
