# Generated by Django 5.2.2 on 2025-06-16 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_remove_cart_payment_payment_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.cart'),
        ),
    ]
