# Generated by Django 5.2 on 2025-06-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_cart_payment'),
        ('pos', '0008_alter_payment_cart'),
    ]

    operations = [
    ]
