# Generated by Django 5.2.2 on 2025-06-17 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_merge_0004_cart_payment_0008_alter_payment_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payment',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pos.cart'),
        ),
    ]
