# Generated by Django 5.2.2 on 2025-07-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_remove_cart_payment_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_info',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
