# Generated by Django 5.2.2 on 2025-07-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_alter_payment_card_info_alter_payment_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_info',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
