# Generated by Django 5.2.1 on 2025-05-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payment_made',
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
    ]
