# Generated by Django 5.2.1 on 2025-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_cart_payment_made_cart_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
